### ISSUE TITLE
Float32Array as input argument

### ISSUE THREAD

**Issue by dy** [compute-io/qmean#3]
Sometimes it is required to calculate rms for typed values, like in `Float32Array` etc. (standard format for _AudioBuffers_ for example), but [this validation check](https://github.com/compute-io/qmean/blob/master/lib/index.js#L42) forces input argument to be plain array.

That would be unreasonable to force creating an array just to make this function work. Especially it is the case for big number of samples, where creating an array is costly.

I guess this case might be true not only for `qmean` package. What politics of compute-io in this respect?

**Comment by kgryte** [comment]
Merged a PR. You should be able to provide a `Float32Array` now.
